# Generated by Django 5.1.1 on 2024-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_email_alter_user_token_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='token_home',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='url_home',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
