# Generated by Django 5.1.1 on 2024-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_security_token_home_security_url_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='token_home',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='security',
            name='url_home',
            field=models.CharField(max_length=255),
        ),
    ]
