# Generated by Django 5.1.1 on 2024-11-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_security_token_home_alter_security_url_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(default='Casa <built-in function id>', max_length=255),
        ),
    ]
