# Generated by Django 5.1.1 on 2024-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(default='Home', max_length=255),
        ),
    ]
