# Generated by Django 5.1.1 on 2024-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
