name: app_user_controller
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.3
  firebase_analytics: ^11.3.3
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/auth.json
